In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [2]:
data = pd.read_csv("salaries.csv")
data

       company                  job     degree  salary_more_then_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

In [3]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['company'] = le.fit_transform(data['company'])
data['job'] = le.fit_transform(data['job'])
data['degree'] = le.fit_transform(data['degree'])

In [4]:
X = data.drop('salary_more_then_100k',axis=1)
y = data['salary_more_then_100k']

In [5]:
y

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: salary_more_then_100k, dtype: int64

In [6]:
y

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: salary_more_then_100k, dtype: int64

In [7]:
data.head()

   company  job  degree  salary_more_then_100k
0        2    2       0                      0
1        2    2       1                      0
2        2    0       0                      1
3        2    0       1                      1
4        2    1       0                      0

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
data

    company  job  degree  salary_more_then_100k
0         2    2       0                      0
1         2    2       1                      0
2         2    0       0                      1
3         2    0       1                      1
4         2    1       0                      0
5         2    1       1                      1
6         0    2       1                      0
7         0    1       0                      0
8         0    0       0                      0
9         0    0       1                      1
10        1    2       0                      1
11        1    2       1                      1
12        1    0       0                      1
13        1    0       1                      1
14        1    1       0                      1
15        1    1       1                      1

In [10]:
dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

In [11]:
dtc.score(X_train, y_train)

1.0

In [12]:
dtc.predict([[2,2,1]])

c:\Users\avika\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0], dtype=int64)

In [13]:
titanic = pd.read_csv('titanic.csv')
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
titanic['Sex'] = le.fit_transform(titanic['Sex'])
titanic['Embarked'] = le.fit_transform(titanic['Embarked'])
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,0
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,2
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,2
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",1,27.0,0,0,211536,13.0000,NaN,2
887,888,1,1,"Graham, Miss. Margaret Edith",0,19.0,0,0,112053,30.0000,B42,2
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",0,NaN,1,2,W./C. 6607,23.4500,NaN,2
889,890,1,1,"Behr, Mr. Karl Howell",1,26.0,0,0,111369,30.0000,C148,0
890,891,0,3,"Dooley, Mr. Patrick",1,32.0,0,0,370376,7.7500,NaN,1

In [15]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    int32
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     891 non-null    int32
dtypes: float64(2), int32(2), int64(5), object(3)
memory usage: 76.7+ KB

In [16]:
titanic['Embarked'].value_counts()

Embarked
2    644
0    168
1     77
3      2
Name: count, dtype: int64

In [18]:
titanic = titanic.drop(['Age','Cabin','Ticket','Name'],axis=1)

In [19]:
titanic

     PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked
0              1         0       3    1      1      0   7.2500         2
1              2         1       1    0      1      0  71.2833         0
2              3         1       3    0      0      0   7.9250         2
3              4         1       1    0      1      0  53.1000         2
4              5         0       3    1      0      0   8.0500         2
..           ...       ...     ...  ...    ...    ...      ...       ...
886          887         0       2    1      0      0  13.0000         2
887          888         1       1    0      0      0  30.0000         2
888          889         0       3    0      1      2  23.4500         2
889          890         1       1    1      0      0  30.0000         0
890          891         0       3    1      0      0   7.7500         1

[891 rows x 8 columns]

In [20]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Sex          891 non-null    int32
 4   SibSp        891 non-null    int64
 5   Parch        891 non-null    int64
 6   Fare         891 non-null    float64
 7   Embarked     891 non-null    int32
dtypes: float64(1), int32(2), int64(5)
memory usage: 48.9 KB

In [21]:
X = titanic.drop('Survived',axis=1)
y = titanic['Survived']

In [22]:
X

     PassengerId  Pclass  Sex  SibSp  Parch     Fare  Embarked
0              1       3    1      1      0   7.2500         2
1              2       1    0      1      0  71.2833         0
2              3       3    0      0      0   7.9250         2
3              4       1    0      1      0  53.1000         2
4              5       3    1      0      0   8.0500         2
..           ...     ...  ...    ...    ...      ...       ...
886          887       2    1      0      0  13.0000         2
887          888       1    0      0      0  30.0000         2
888          889       3    0      1      2  23.4500         2
889          890       1    1      0      0  30.0000         0
890          891       3    1      0      0   7.7500         1

[891 rows x 7 columns]

In [23]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [25]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [26]:
dt.score(X_train, y_train)

1.0

In [28]:
y_pred = dt.predict(X_test)

In [29]:
accuracy_score(y_test, y_pred)

0.7374301675977654